### ISSUE TITLE
display of c64 logo

### ISSUE THREAD

**Issue by pacav69** [willasm/c64opcodes#1]
the c64 logo fails to be displayed on all opcode pages

**Comment by willasm** [comment]
I can confirm this. Also, all the navigation buttons at the bottom of every page, and the CSS do not work any more. Even the c64 font will not be displayed.

This has to be caused by a vscode update, most likely some security policy they added for displaying html. I'll need to track down what they changed to correct this. At least for the now the text is still being displayed. Give me a while to track down what they changed and hopefully it will not require any big changes.

**Comment by pacav69** [comment]
FYI i was using the latest vscode 
Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:52:33.687Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 20.6.0

**Comment by willasm** [comment]
Sorry I have not responded sooner. I just finished up another extension that I have been meaning to finish for some time now and now that it has been uploaded I can spend more time on this problem. I wrote this extension 2 years ago (this was actually only the second vscode extension I had written at the time), so it has been a long time since I have looked at the code. The last time I did any programming on my c64 was just over a year ago and the extension was still working fine at that time, so it has to be a change in an update that was done to vscode during that time. I did spend a couple hours on it this past week, but without much success. I do recall that getting it to load external html files was not an easy task but at the time I wanted it that way to make updating the html much easier. I may need to change that approach.

I think I'll whip up a small test extension just to figure out how to get it to display just a single html page with images and css. That will be far quicker than going through all this extensions code (There is around 100 code files in this extension). Once I figure what what I need to do to get the webview to display everything correctly, applying the changes to this extension should be relatively easy to do (I hope). I suspect it is a change to vscode's webview itself that is the issue. When I wrote this extension the webview was a relatively new addition to vscode so I'm sure it has had many changes made to it since then.

I will let you know as soon as I have any successful progress on this. William.

**Comment by pacav69** [comment]
One of the reasons i was interested in this extension is that it can assist a beginner programmer in doing C64 code and perhaps add some additional opcodes for the 65c02 that is used in the commander x16. Perhaps make a new extension specifically for the Commander x16.

**Comment by willasm** [comment]
That is a great idea. Have been meaning to have a closer look at the instruction set for the x16 ever since the first working prototypes were shown on the 8-bit Guy's channel. It is actually supposed to start being sold by the end of February. That would definitely be worthy of its own extension, I believe the instruction sets are similar but there are a lot of differences. I will look into it.

**Comment by pacav69** [comment]
the commander x16 uses a w65c02 which has the 6502 opcodes plus a  few more with a bit of additional work on the c64 version it would be a great assest. At present i'm working on a development enviroment that will allow users to have the tools to create and test apps.

**Comment by willasm** [comment]
Well I can get it working in my test extension. Instead of loading from the external file `adc.html` I just moved it into the test code itself. It has to be a security thing they added that is preventing loading from an external html file.  I will probably just end up re-writing this from scratch to avoid the whole problem. Even if I can get it working again using external files, they could make another change that could potentially just break it again. This was actually only my second program I ever wrote in Javascript so there is definitely many improvements I can make to the code. The good thing is all the html is already done which was by far the most time consuming part of the writing the original extensions code. This would also give me the opportunity to add support for the commander x16's additional instruction set, just need to research for different opcodes compared to the 6502. If you have any links or info regarding the x16 you could help by sending them to me. You can use my email `willmck63@gmail.com` for that rather than having to post here.

Anyhow, here is a screenshot of my test extension on the right and the original on the left. The image and css are loading correctly. Still need to test if the javascript for the buttons works or not but I'll need to add more pages to it so they have somewhere to link to...

![TestShot](https://github.com/willasm/c64opcodes/assets/94352899/eee79e95-cde2-42cb-b764-b537afac1952)

**Comment by willasm** [comment]
Good news, I found the problem in the extension and have it working. I did find a bug though. If I enable the c64 font in the settings, it does use it the first time, but if I use the navigation buttons and go to another opcode it stops using it for some reason? I need to track that down. I will upload an update as soon as I fix that bug. I am still interested in adding the commander x16 extra opcodes though as that is a great idea.

Quick picture of it working...

![Fixed](https://github.com/willasm/c64opcodes/assets/94352899/b2054ada-c0ab-4e49-aae6-4838d3233cc2)

**Comment by willasm** [comment]
Bug has been fixed and the extension has been uploaded as v1.0.0 and is available in VSCode now.
By the way, thank you for bringing this to my attention. It may have been some time before I noticed as I have not done any c64 programming in a long time.

**Comment by pacav69** [comment]
looks good to me great work. At first i thought i could fix it but it was not an easy task.

**Comment by pacav69** [comment]
i've installed the latest version and every thing looks fine

**Comment by willasm** [comment]
Thanks for testing. The problem was with the Uri's for the resources. I had to make changes to them to be compliant with the current webview in vscode. It was a bit tricky finding that as the old ones were working fine before.

**Comment by pacav69** [comment]
No problem glad i could help

**Comment by pacav69** [comment]
I think you can close this issue off as the problem has been fixed
